spring.application.name=SmartShop
spring.datasource.url=jdbc:postgresql://localhost:5432/smartshop_db
spring.datasource.username=postgres
spring.datasource.password=mohamed@1230
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update